### ISSUE TITLE
Unable to buy credits / update account

### ISSUE THREAD

**Issue by torstentors** [resonatecoop/website#72]
When clicking “Checkout” on `https://id.resonate.coop/checkout` I received this error:

`{“code”:“parameter_invalid_empty”,“doc_url”:“[Error codes | Stripe Documentation](https://stripe.com/docs/error-codes/parameter-invalid-empty%22,%22status%22:400,%22message%22:%22You) passed an empty string for ‘line_items’. We assume empty values are an attempt to unset a parameter; however ‘line_items’ cannot be unset. You should remove ‘line_items’ from your request or supply a non-empty value.”,“param”:“line_items”,“request_id”:“req_HTM6vJghChrTQM”,“type”:“invalid_request_error”}`

**Comment by peterklingelhofer** [comment]
@torstentors thanks for reporting this. Can you turn off any adblockers and try again if any are on? It seems like it's making the call to Stripe but the part that tells it what you want to purchase specifically (how many credits) isn't coming through.

**Comment by torstentors** [comment]
Thanks Peter for getting back!

Yes, it was the adblocker. Now it works!* Thanks!

 *(Until I come to the place where I can't pay via paypal or money
transfer. Even my stripe account isn't shown as an option).

Am Freitag, dem 23.12.2022 um 09:42 -0800 schrieb peterklingelhofer:

**Comment by peterklingelhofer** [comment]
Hey @torstentors, glad disabling the adblock got you further along. Can you provide a screenshot of what you're seeing on the Stripe side now so I can try to isolate the problem? Thank you!

**Comment by rupl** [comment]
Howdy 👋🏼  I'm seeing the exact same error, but unfortunately no additional screenshot to provide.

It appeared as unformatted JSON in the browser window exactly as printed in the OP (aside from the `request_id`). After I saw that JSON once, I hit back and tried to purchase credits a second time. Now it reloads the account page, but doesn't show the error anymore. Some browsers never show the JSON, but just reload the account page without a redirect to the payment screen. I reproduced in multiple browsers:

MacOS Ventura 13.6
- FF 118.0.1 (64-bit)
- Brave v1.58.135, Chromium 117.0.5938.140
- Chrome 117.0.5938.132 (Official Build) (x86_64)

**Comment by rupl** [comment]
Ok, I tried it a couple more times and chose to add some Membership shares, and that's when I came to the raw JSON. When supporter shares were added (instead of just credits) I got to the "Checkout" button, but it's totally blank. I tried the process again in the browsers mentioned above (with their default settings, and with respective request blocking settings disabled), and all behave the same when I add supporter shares instead of just listening credits.

Here are screenshots:

<img width="591" alt="Screenshot 2023-10-05 at 11 02 32" src="https://github.com/resonatecoop/website/assets/254753/320ab50d-959d-4b4e-a1e9-0642802395bb">

<img width="658" alt="Screenshot 2023-10-05 at 10 59 07" src="https://github.com/resonatecoop/website/assets/254753/5e408702-2048-4323-beb0-76c6c9d34a87">

**Comment by rupl** [comment]
Hello again, I wanted to resume using my Resonate account in the new year, but the page is still unable to provide me with a checkout screen to pay. While reviewing this issue I noticed the original poster seems to be from Germany. I'm also based in Germany. Just throwing that out there in case it can be a factor in debugging.

**Comment by simonv3** [comment]
Hey @rupl. Resonate isn't actively maintained at the moment. I'd check out the [community forum](https://community.resonate.coop/) for updates.
